# Generated by Django 3.1.10 on 2021-05-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('crypto', models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('bch', 'bch')], max_length=10)),
                ('page', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=200)),
                ('crypto', models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('bch', 'bch')], max_length=10)),
            ],
        ),
    ]
